### ISSUE TITLE
Thaumcraft Wands don't work properly

### ISSUE THREAD

**Issue by DarianLStephens** [c0508383/Backhand#11]
When attempting to use an offhand wand, it will get stuck in its firing mode with no animation.

![2022-08-10_13 54 47](https://user-images.githubusercontent.com/15375876/183809502-d058deb3-8e4c-4559-b0b2-75a421f8ca75.png)
It also seemingly has no vis cost.

**Comment by c0508383** [comment]
Renders a little weirdly, and won't show the focus GUI at the top left or let you change your focus while in the offhand, but fixed! I hope you can see it in the video, but vis does go down as you're casting it in the offhand now too. Thank you so much, this mod's really cool!

https://streamable.com/7lcqbk

**Comment by DarianLStephens** [comment]
I wonder if you could actually flip offhand items onscreen? Like, invert their scale or something. That should massively improve situations like this.
