### ISSUE TITLE
Main Hand doesn't animate correctly

### ISSUE THREAD

**Issue by DarianLStephens** [c0508383/Backhand#12]
When placing a block or using an item, the main hand will just... turn a bit, with no swinging animation.
![2022-08-10_13 57 09](https://user-images.githubusercontent.com/15375876/183809792-0e0133fb-4971-41ab-986c-0a45b1e5154e.png)

The offhand works fine, however.
![2022-08-10_13 57 00](https://user-images.githubusercontent.com/15375876/183809762-8c466a53-2990-4290-ab36-55f255dc2e33.png)

**Comment by c0508383** [comment]
I'm not getting this issue on my side. What other mods are you using?

**Comment by DarianLStephens** [comment]
Yeah, it looks like it was a conflict with something, since it was fine when I used Backhand alone, or with a very minimal mod set.
I'll try to figure out what's causing the problem.

**Comment by c0508383** [comment]
I did end up seeing this issue when testing having another player in multiplayer swing their offhand, your hand moves a bit like this too. Hopefully the fix I made for that fixes this too, I think it should. If it doesn't, please open up the issue again. Thank you!!
