### ISSUE TITLE
 Blacklist doesn't work on mod items

### ISSUE THREAD

**Issue by kotmatross28729** [c0508383/Backhand#13]
I added the flans crossbow and the et futurum requiem crystal to the blacklist, but I can still take them.
![Base Profile Screenshot 2022 08 11 - 14 58 36 43](https://user-images.githubusercontent.com/110309314/184128578-5f9971fe-d030-44c3-bccb-e80146290cc9.png)
![Base Profile Screenshot 2022 08 11 - 14 58 46 15](https://user-images.githubusercontent.com/110309314/184128585-a5f10ab3-176e-493a-a7c4-55e1472140c1.png)

here is the config settings

    # These items will be unable to be swapped into the offhand.
    # Formatting of an item should be: modid:itemname
    # These should all be placed on separate lines between the provided '<' and '>'.
    S:"Blacklisted items" <
	minecraft:iron_sword
	flansmod:crossbow410
	minecraft:compass
	etfuturum:end_crystal
     >

**Comment by c0508383** [comment]
Fixed! Thank you for your report!
