### ISSUE TITLE
 Bow turns into arrows with effects when you hold an arrow in your left hand

### ISSUE THREAD

**Issue by kotmatross28729** [c0508383/Backhand#14]
https://user-images.githubusercontent.com/110309314/184166838-328a5fd6-4278-425d-9a91-757547d15e23.mp4

**Comment by c0508383** [comment]
Currently not getting this issue when playing with only Et-Futurum. Please send me a list of mods so I can narrow down which one is conflicting with Backhand and make it compatible!

**Comment by c0508383** [comment]
https://streamable.com/wpmfrd
