### ISSUE TITLE
Inventory Slot missing with mods altering the inventory

### ISSUE THREAD

**Issue by DarianLStephens** [c0508383/Backhand#15]
For example, using [the Satchels mod](https://www.curseforge.com/minecraft/mc-mods/satchels), the slot is just completely gone.
![2022-08-13_00 55 54](https://user-images.githubusercontent.com/15375876/184382415-d15a2976-39a2-4617-ad10-bc479776349b.png)
![2022-08-13_00 56 41](https://user-images.githubusercontent.com/15375876/184382422-e0b5d8da-29ca-4300-87c8-2a7448f67d86.png)

Maybe it's related to Satchel's alterations to the inventory to support its satchels?

**Comment by DarianLStephens** [comment]
Even if I turn off Satchels' inventory tab, the new slot still doesn't show up.
![2022-08-13_00 58 33](https://user-images.githubusercontent.com/15375876/184382859-0d4703d5-c6fe-428f-8444-92aa14fe25f6.png)

Both posts were tested with only Backhand and Satchels, with the first image just having Backhand & CodeChickenCore(?).

**Comment by c0508383** [comment]
This isn't a bug, it's a feature B)

But in all seriousness, I can't have both the creative slot with mods that modify the inventory without serious issues, so the mod moves your offhand slot to a slot in the inventory instead. You can configure what slot this is, and still hotswap into the offhand as well. Later on, I might add compatibility for those sorts of mods.
