### ISSUE TITLE
Opening doors with offhand item doesn't work

### ISSUE THREAD

**Issue by DarianLStephens** [c0508383/Backhand#16]
It plays the sound twice, so it seems like it's interacting with the door two times instead of once.
![2022-08-13_01 09 34](https://user-images.githubusercontent.com/15375876/184384965-353bc535-6d49-4175-8a72-da364bd4edf9.png)

If you have a placeable item in your main hand at the same time, it works, but things like swords don't
![2022-08-13_01 09 48](https://user-images.githubusercontent.com/15375876/184385248-c09e4fcf-5d77-49f0-b011-9f36c030c2ac.png)
![2022-08-13_01 09 58](https://user-images.githubusercontent.com/15375876/184385261-d889f853-05dc-4cbb-9205-c10473c361cb.png)
.

**Comment by c0508383** [comment]
Fixed! This fix will be available in a build later in the winter. Thank you.
