### ISSUE TITLE
Problem with the first slot of the backpack

### ISSUE THREAD

**Issue by Omgise** [c0508383/Backhand#18]
![A89E3769CE3F09CAF418B48DEAD2F7B8](https://user-images.githubusercontent.com/106000018/186826900-cbeb1111-5350-4091-955e-a2a8e746394f.gif)

**Comment by Omgise** [comment]
> Invtweaks is always in my dev environment, I don't seem to be getting these errors. Please provide a full mod list!

This is a list of my mods
[lme_export.txt](https://github.com/c0508383/Backhand/files/10183128/lme_export.txt)

**Comment by c0508383** [comment]
> > Invtweaks is always in my dev environment, I don't seem to be getting these errors. Please provide a full mod list!
> 
> This is a list of my mods [lme_export.txt](https://github.com/c0508383/Backhand/files/10183128/lme_export.txt)

Sorry for the follow up, but could you send me a link to a zip folder containing all of your mods? There's a lot of possible offenders here.

**Comment by Omgise** [comment]
The Offhand slot still does not render correctly with the Satchels mod, and the error can still be reproduced with inventory tweaks in Backhand mod v1.2.1 after the Satchels mod is removed

**Comment by Omgise** [comment]
This is the unofficial version of the Inventory Tweaks mod that I use:https://github.com/GTNewHorizons/inventory-tweaks

**Comment by Omgise** [comment]
> This is all my mods: https://drive.google.com/file/d/1rwgeqLDhTmVXkZK824Pa3bowmZ3_6YHN/view?usp=share_link

Here's my config file, if you need it, in case you crash my mods due to id conflicts while testing them :)
[config.zip](https://github.com/c0508383/Backhand/files/10191812/config.zip)
