### ISSUE TITLE
Crash when eating food while holding a torch in the offhand (or probably any other item in the slot)

### ISSUE THREAD

**Issue by Desempregago** [c0508383/Backhand#20]
[Crash Report](https://hastebin.com/amirucixum.properties)

• Backhand 1.2.0
• No BattleGear
• No Offhand Mod

**Comment by Desempregago** [comment]
Do I need MysteriumLib?

**Comment by c0508383** [comment]
Please send a new crash report, that one's empty. I'm also not getting this crash on my end running just Backhand. Are there any mods you're running while doing this?

**Comment by c0508383** [comment]
Closing because of the age of the issue, and it doesn't seem to be happening anymore. Feel free to reopen the issue if this crash persists in later versions.
