### ISSUE TITLE
The battle sign in TC on the left hand cant protect player properly

### ISSUE THREAD

**Issue by iamsoNewBee** [c0508383/Backhand#24]
![image](https://user-images.githubusercontent.com/98573273/190298514-36c3c584-b5e7-49ed-9fa3-1697c76b6070.png)
This picture reflects the same situation in theoffhandmod

**Comment by c0508383** [comment]
Fixed! This and many other items in first person are now mirrored correctly.

**Comment by iamsoNewBee** [comment]
but how could i use my left hand tools by right click?i can only use its left click?
