### ISSUE TITLE
Has issues with LOTR.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#25]
Offhand slot doesn't render on the hotbar.
Offhand 'hand' doesn't render.

Tested with/without other mods besides LOTR, same issue.

**Comment by DarianLStephens** [comment]
The only issue I'm having here is the hotbar slot not rendering:
![2022-11-09_10 48 22](https://user-images.githubusercontent.com/15375876/200700859-46b50443-8a95-4eca-a3fc-54b8a26b8fe8.png)
Heck, even the inventory slot works, surprisingly!
![2022-11-09_10 49 15](https://user-images.githubusercontent.com/15375876/200700890-cb3bf07d-75ab-4321-b709-0fc569075aa3.png)

**Comment by MagmaBro123** [comment]
@DarianLStephens Btw, you may need to look into supporting LOTR's weapon stats/modifiers and whatnot.

**Comment by c0508383** [comment]
I've fixed the slot not rendering in the hotbar, and the hand does seem to render when the correct configs are enabled. Thank you for the report!
