### ISSUE TITLE
crash when... open inventory?

### ISSUE THREAD

**Issue by kotmatross28729** [c0508383/Backhand#26]
this is exactly what happens in the tab et futurum with items
the list of mods in crashlog
crash : https://pastebin.com/GAWfidvY

**Comment by c0508383** [comment]
I'm only getting this crash on Et-Futurum 2.4.1, with or without the creative GUI inventory. I'm not getting the crash anymore outside of a dev environment, but I've added a config to disable the creative inventory offhand slot. Reopen this issue if it still happens with that config set to false after the coming update.
