### ISSUE TITLE
MPM+ makes an empty offhand render weirdly. Add MPM support.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#27]
Title. I am using other mods currently, but this also occurs on a blank instance with just MPM+.

![2022-12-08_14 48 28](https://user-images.githubusercontent.com/51277766/206574677-09208d17-20c6-46d1-b123-5d83acdb2afc.png)

**Comment by c0508383** [comment]
Good catch, this has been fixed on the dev branch. Thank you!!
