### ISSUE TITLE
LOTR's Crossbows are rendered weirdly in the offhand.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#28]
Title. Noticed that 1.2.1 actually fixed quite a few issues, including the pickblock ghost item one too.

LOTR still has some minor issues with certain items though. Its 'loaded' Crossbows from what I've seen.

![2022-12-08_14 59 59](https://user-images.githubusercontent.com/51277766/206576598-f6c85beb-e21e-4e37-ad42-78ce2d083cf6.png)
![2022-12-08_15 03 00](https://user-images.githubusercontent.com/51277766/206576854-c73110ca-49af-4cde-921f-7ee42b9d48c8.png)

**Comment by c0508383** [comment]
Fixed! I'll need to come up with a fix for arm aiming, but there may not be a general solution for that. Thanks for the report!

**Comment by MagmaBro123** [comment]
Again, Rudy's Battleworks mod handles LOTR's weapons much better, so I'd recommend asking how he did it for his mod.
