### ISSUE TITLE
Add a config option (like how the blacklist works) to make weapons "two-handed".

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#29]
Title.

If a weapon is marked as two-handed, any other item in the opposite hand slot will heavily reduce the damage and speed (via mining fatique, or, if LOTR is installed and an option is enabled, reduce the weapon's Melee Speed modifier) of both weapons, or could simply prevent any attack action from being registered at all.

**Comment by c0508383** [comment]
You're welcome to send me feature requests over discord like this one, (and this is a good one!) but please keep the issue tracker bug/issue oriented. Thank you for the suggestion!

**Comment by MagmaBro123** [comment]
Alright, sorry. Your usually inactive most of the time (Ik, IRL stuff), so its kinda hard to know when you'll respond.
