### ISSUE TITLE
Offhand breaking blocks creates ghost blocks. Clicking on said blocks makes thhem appear again.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#30]
Title. Not caused by other mods.

**Comment by c0508383** [comment]
Can you send a video of this issue? I haven't been able to reproduce it at all.

**Comment by MagmaBro123** [comment]
Hold a tool in your offhand, and try breaking blocks in creative with your offhand.

**Comment by c0508383** [comment]
Didn't know this was a creative-only issue, it's fixed now. Thank you!

**Comment by MagmaBro123** [comment]
No problem. Sorry for not mentioning, oops lol.
