### ISSUE TITLE
WHEN U PICK UP ITEM WHICH YOUR BACK HAND HOLDS,THE NUMBER OF WHICH WOULDNT CHANGE

### ISSUE THREAD

**Issue by iamsoNewBee** [c0508383/Backhand#41]
ONLY AFTER PRESSING F TO SWITCH YOUR HAND, THE NUMBER CHANGES TO CORRECT

**Comment by c0508383** [comment]
This only seems to happen when using an inventory slot for your offhand, fixed! Thank you, and also CAPS ON BROTHER >:D

**Comment by iamsoNewBee** [comment]
LOOKING FOR THE 1.30 :D
