### ISSUE TITLE
Can't change CreativeInventoryOffhand in config

### ISSUE THREAD

**Issue by marlester-dev** [c0508383/Backhand#42]
Can't change CreativeInventoryOffhand in config. It's not a boolean, I can't change it, there is no true false.

This setting always resets after game restart, very annoying.

I have serious bugs when this is set to false, my items bug and duplicate in creative mode when this is set to false.

**Comment by c0508383** [comment]
Sorry for the trouble, that's a pretty nasty inconvenience. Good catch, thank you!
