### ISSUE TITLE
OF Dynamic Lights don't work with offhand

### ISSUE THREAD

**Issue by marlester-dev** [c0508383/Backhand#43]
When I hold a torch in main hand, OptiFine Dynamic lights work, but when I hold it in the offhand, it does not work.
Offhand is useless for me at the moment, I will uninstall this mod :(
![gifg](https://user-images.githubusercontent.com/77095872/211745816-3c74dc12-5ed2-422f-a15b-d58cc1bbfed4.gif)

**Comment by MagmaBro123** [comment]
Known.

https://github.com/c0508383/Backhand/issues/22

**Comment by c0508383** [comment]
Closing this, yep duplicate report.
