### ISSUE TITLE
Bug with GTNH fork of NEI

### ISSUE THREAD

**Issue by Polarite** [c0508383/Backhand#44]
Cant interact with inventory after looking up a recipe, issue gets solved after removing backhand.

https://github.com/GTNewHorizons/NotEnoughItems/issues/332

https://paste.ee/p/zpSnk

**Comment by aking4125** [comment]
This is still a problem. Removing the backhand fixes the issue. 

For us, it's more than just the inventory. Anything that opens any type of GUI doesn't work including the pause menu and chat. Dying results in a glitched screen as well.

**Comment by DarianLStephens** [comment]
Same here. It breaks every GUI once whatever condition is reached.
Nothing can be opened. Even alt-tabbing the game doesn't open the pause menu.
The only way out is to completely close the game.

**Comment by c0508383** [comment]
Should be fixed, it was a severe coding issue on my end that kept GUIs from being opened to prevent Backhand's container mismatching with other containers. Really sorry about this, it's a huge bug that's been around for a long while.

If the issue persists after the next update, shoot me a message and I'll reopen this and get back to it ASAP.

Thank you all for your patience and the report!

**Comment by DarianLStephens** [comment]
It's a shame you couldn't keep the offhand slot.
Even if it was some weird special thing that wasn't _technically_ a slot, but didn't necessitate you replacing the player inventory container.
But, I'll take it in exchange for being able to play the modded game with Backhand again.
