### ISSUE TITLE
Inventory is pretty buggy while Backhand is in use.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#45]
Title. See video below.

https://user-images.githubusercontent.com/51277766/213636641-f9132b93-d85a-4fe2-9fe7-9807a36aced6.mp4

Modlist:
https://www.dropbox.com/s/84nvbftlffioh5k/modlist.zip?dl=0

**Comment by c0508383** [comment]
This funkiness in particular has been fixed, sorry about that! Thank you for the report.

**Comment by MagmaBro123** [comment]
Np. This has been a pretty long-standing issue for a while, glad its fixed.
