### ISSUE TITLE
MANY GUI CRASHES WHEN U ENABLED INVENTORY SLOT

### ISSUE THREAD

**Issue by iamsoNewBee** [c0508383/Backhand#47]
AND /GAMEMODE 0/1/2 ARE NOT AVAILABLE

**Comment by MagmaBro123** [comment]
No need to use all caps. A crash report would help too.

**Comment by iamsoNewBee** [comment]
[minecraft-exported-crash-info-2023-01-21T08-53-56.zip](https://github.com/c0508383/Backhand/files/10471210/minecraft-exported-crash-info-2023-01-21T08-53-56.zip)
IT`S NOT A CRAHSE BUT RETURN TO THE TITLE INTERFACE.I COLSED IT BY MYSELF AND GENERATED IT.

**Comment by iamsoNewBee** [comment]
[2023-01-21-1.log.gz](https://github.com/c0508383/Backhand/files/10471214/2023-01-21-1.log.gz)
MAYBE THIS HELPS TOO

**Comment by c0508383** [comment]
The inventory slot is currently not meant to be used with all mod containers, it's purely optional and should be disabled if experiencing crashes. I won't be adding more compatibility for the slot feature (I've tried and it gets buggy), but I may add a new inventory tab for just the slot.

Closing this for now, let me know if you still experience crashes after disabling the config.

**Comment by iamsoNewBee** [comment]
IF DISABLING IT, IT CAN BE USED CURRENTLY.
