### ISSUE TITLE
Is there any way to compile Backhand? Says something's missing a tools.jar.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#50]

**Comment by makamys** [comment]
`./gradlew setupDecompWorkspace` followed by `./gradlew build` works for me.

Make sure you're on the `dev`  branch and not the `master` branch I guess.

**Comment by MagmaBro123** [comment]
Same issue. Build fails.

![image](https://user-images.githubusercontent.com/51277766/214140239-c453c5a4-1574-4878-942c-6f5fe26481de.png)

**Comment by c0508383** [comment]
Everything's working for me too, follow these steps:
1. Download and install Github Desktop.
2. Clone with Github Desktop by clicking the <Code> button, then the Open With Github Desktop button.
3. Open the project in IntelliJ by double-clicking the build.gradle file (has a g inside a green circle). Some stuff should start downloading, and text should appear in some console.
4. After everything from the build.gradle finishes, you should notice it can't find forge 1.7.10 in red letters (This is good, you're on the right track!). Go over to the Gradle tab on the right. Under tasks -> forgeGradle, double click setupDecompWorkspace. This should start a gradle task. Wait for it to finish.
5. Click the refresh button in the Gradle tab. The mod should now be built.
