### ISSUE TITLE
Make the Offhand do the popup animation thingy. (or whatever I should call it.)

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#53]
Title.

When selecting an item, it jumps up.
However, this doesn't work with the offhand, and the item simply pops up out of thin air.

Also, pick-blocking items from the Creative inventory seems to still cause ghost items.

(Also, LOTR's alignment bar seems to bug out while an item is in the offhand.)

https://user-images.githubusercontent.com/51277766/221112604-c024748c-4569-4e98-9d9e-1f9a0cca5fc1.mp4

**Comment by c0508383** [comment]
Just fixed the popup animation and that alignment bar error for LOTR, and I believe I've fixed ghost items from creative on dev as well. Thanks for the report!

**Comment by MagmaSlime123** [comment]
This issue seems to only occur when Render empty offhand is disabled.

https://github.com/c0508383/Backhand/assets/51277766/eabda0a6-88b8-4e13-ad28-896a973ece7f
