### ISSUE TITLE
I think you broke something...

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#54]
Latest commit, (sorry for posting these issues if I shouldn't. Not sure if you're noticing them as fast as I am lol)

![2023-02-24_10 51 47](https://user-images.githubusercontent.com/51277766/221252887-7dbcc770-23b8-4408-9293-3ffaeb97b0e4.png)

**Comment by c0508383** [comment]
Fixed just now, please wait a while before submitting an issue report about something on the dev branch. There's issues I notice and fix pretty quickly. Thank you.

**Comment by MagmaBro123** [comment]
Noo problem, sorry.
