### ISSUE TITLE
Make the LOTR Pouch button move to better places in the Survival GUI if the Offhand slot is enabled.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#55]
Title. With Backhand, the LOTR Pouch button seems to love moving into weird areas of the inventory.

Not sure if this is possible to fix, but it'd be nice if the pouch button stayed at its default position, rather then doing whatever its doing, as shown below.

(Also, there's still a few open issues that've gotten fixes, such as #46, which should be closed)

![2023-02-24_11 03 51](https://user-images.githubusercontent.com/51277766/221256073-48dce674-b939-42ce-ba40-d37607f9d1f2.png)
![2023-02-24_11 03 55](https://user-images.githubusercontent.com/51277766/221256076-2ac5383b-5147-416c-a2b7-9ae0cc3b4e66.png)

**Comment by c0508383** [comment]
I'll reopen this if I can find a non-invasive way to move that button around. I suggest disabling the extra inventory GUI slot to avoid this issue for now, and using the hotkey instead.

**Comment by MagmaBro123** [comment]
Alright.
