### ISSUE TITLE
When leaving Nether Dimensions, the item on Offhand will disappear

### ISSUE THREAD

**Issue by Omgise** [c0508383/Backhand#56]
https://user-images.githubusercontent.com/106000018/221342565-cee4dda5-b15a-4fab-8170-bb04eebd4cf8.mp4

**Comment by Omgise** [comment]
When you leave or enter Dimensions, the items on Offhand will disappear :)

**Comment by c0508383** [comment]
All fixed! Thanks for the report.
https://streamable.com/hep1e8
