### ISSUE TITLE
Weird visiual issues when hovering on items and scrolling in the creative UI.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#58]
Title. Notice the hotbar too.

https://user-images.githubusercontent.com/51277766/221388412-2b126de7-5769-4520-8fb6-6b152eb0ebb1.mp4

**Comment by c0508383** [comment]
Not getting this bug anymore. Can you give me some tips on how to recreate this, and a mod list too?

**Comment by MagmaSlime123** [comment]
Just scroll through the inventory like normal. There's nothing special needed. If this is fixed by the latest version somehow then, great.

**Comment by c0508383** [comment]
That seems to be the case. Thanks for the report!
