### ISSUE TITLE
crash when i use bows with the backhand/offhand

### ISSUE THREAD

**Issue by branman5949** [c0508383/Backhand#59]
heres my crash report, log and config i used 
[crash-2023-03-21_02.59.29-client.txt](https://github.com/c0508383/Backhand/files/11025570/crash-2023-03-21_02.59.29-client.txt)
[backhand.txt](https://github.com/c0508383/Backhand/files/11025573/backhand.txt)
[fml-client-latest.log](https://github.com/c0508383/Backhand/files/11025574/fml-client-latest.log)
[latest.log](https://github.com/c0508383/Backhand/files/11025578/latest.log)

**Comment by c0508383** [comment]
Fixed! Thanks for the report. https://streamable.com/3wzzdp
