### ISSUE TITLE
Graphics bug with shaders

### ISSUE THREAD

**Issue by kotmatross28729** [c0508383/Backhand#6]
If you take an item in your left hand and shaders are on, then the item will start go through the wall
Here are the screenshots:
![2022-08-05_16 53 03](https://user-images.githubusercontent.com/110309314/183263471-b122f755-25d9-4e9d-9554-ccbab1e8dae8.png)
![2022-08-05_16 53 15](https://user-images.githubusercontent.com/110309314/183263514-1274cb8c-b374-4bfc-a24d-4efce07188a6.png)

**Comment by c0508383** [comment]
Fixed! Optifine can be tricky.
