### ISSUE TITLE
Incompatibility Issue: JRMC/Dragon Block C

### ISSUE THREAD

**Issue by branman5949** [c0508383/Backhand#61]
When i open the DBC character/item menu (it open when you press the left control key and E key) with the Backhand mod it ends up crashing...
https://dl.jingames.net/
[crash-2023-05-04_15.05.22-client.txt](https://github.com/c0508383/Backhand/files/11400622/crash-2023-05-04_15.05.22-client.txt)
[fml-client-latest.log](https://github.com/c0508383/Backhand/files/11400630/fml-client-latest.log)
[latest.log](https://github.com/c0508383/Backhand/files/11400631/latest.log)

**Comment by c0508383** [comment]
DBC bugs are always tricky, but thankfully I got this one down. Thanks for the report! https://streamable.com/fu1d9t
