### ISSUE TITLE
Crash with CustomNPC+

### ISSUE THREAD

**Issue by branman5949** [c0508383/Backhand#62]
when i go to spawn a mob that was created prior to installing backhand. they crash upon interaction with the backhand mod installed with customnpc+

https://www.curseforge.com/minecraft/mc-mods/customnpc-plus/files
[crash-2023-05-28_13.29.32-server.txt](https://github.com/c0508383/Backhand/files/11585298/crash-2023-05-28_13.29.32-server.txt)
[latest.log](https://github.com/c0508383/Backhand/files/11585300/latest.log)
[fml-client-latest.log](https://github.com/c0508383/Backhand/files/11585303/fml-client-latest.log)

**Comment by c0508383** [comment]
This bug seems to be unrelated to the either mod, and I haven't been able to replicate it anymore while using the latest version of CNPC+. I'll reopen if the issue persists exclusively with Backhand, but I'm closing this for now.
