### ISSUE TITLE
Crash with Inventory tweaks

### ISSUE THREAD

**Issue by 8bitminerman** [c0508383/Backhand#63]
[crash-2023-06-03_14.08.04-client.txt](https://github.com/c0508383/Backhand/files/11643522/crash-2023-06-03_14.08.04-client.txt)
I don't know if this is the correct way to submit this.

When I middle click to sort my inventory the game crashes.

**Comment by c0508383** [comment]
Decided to completely scrap the custom container the mod has at the moment, fixed this bug and possibly many others! Thank you for the report.
