### ISSUE TITLE
When offhand holds an item, the products produced by the furnace will disappear

### ISSUE THREAD

**Issue by Omgise** [c0508383/Backhand#64]
https://github.com/c0508383/Backhand/assets/106000018/e32e2251-fa20-413e-ac5a-cc52c449a75e

**Comment by Omgise** [comment]
After testing, the melted product can still be extracted, but it appears to be invisible

**Comment by c0508383** [comment]
Not getting this error on my end, can you send a mod list?

**Comment by Omgise** [comment]
> Not getting this error on my end, can you send a mod list?

[exports.zip](https://github.com/c0508383/Backhand/files/11644771/exports.zip)

**Comment by c0508383** [comment]
You've got a lot of em, is there anyway you can make a dropbox link with the mods and send it over? If not I can go and look for the mods, it'll just take time.

**Comment by Omgise** [comment]
> You've got a lot of em, is there anyway you can make a dropbox link with the mods and send it over? If not I can go and look for the mods, it'll just take time.

Of course, I will send you the configuration file together  :)

**Comment by c0508383** [comment]
Thanks a ton!

**Comment by Omgise** [comment]
https://drive.google.com/file/d/15to3HzmhY3b-kEVKm5bUiKlUrzVMKdNN/view?usp=sharing

**Comment by Omgise** [comment]
https://www.dropbox.com/s/bqpf6qaqdlcbt9s/test.zip?dl=0

**Comment by c0508383** [comment]
Unrelated, but this collection rocks holy

**Comment by c0508383** [comment]
All fixed, I've decided to completely scrap the custom inventory container I made for the offhand slot. New GUI coming in another update.

Thank you for the report!

**Comment by Omgise** [comment]
The 1.4.0 version still does not fix this issue
[This is a video link](https://www.dropbox.com/s/kc679d7gsm5tkov/Java%202023.06.04%20-%2020.22.22.05.mp4?dl=0)

**Comment by Omgise** [comment]
Maybe the GUI is out of sync? 🤔 @c0508383

**Comment by Omgise** [comment]
@c0508383   Oh I see, the `Offhand Tick Hotswap` caused the problem, when you turn it off, the GUI is no longer locked
