### ISSUE TITLE
Strange position of hands with a map

### ISSUE THREAD

**Issue by kotmatross28729** [c0508383/Backhand#8]
![Base Profile Screenshot 2022 08 09 - 16 07 54 80](https://user-images.githubusercontent.com/110309314/183654751-e5662c3c-c06e-4aac-bb78-a6b46596daa3.png)

**Comment by c0508383** [comment]
Maybe you're just holding the bread real close while trying to fumble around the map?

...yeah I'll try and find a fix for this

**Comment by kotmatross28729** [comment]
> Maybe you're just holding the bread real close while trying to fumble around the map?
> 
> ...yeah I'll try and find a fix for this

Hmm, I now tried to do it differently, but it still looks unnatural.
![Base Profile Screenshot 2022 08 10 - 20 55 11 11](https://user-images.githubusercontent.com/110309314/183983379-471fb745-7b8f-4b5d-b1ac-9aacec2f0fd0.png)
![Base Profile Screenshot 2022 08 10 - 20 55 18 90](https://user-images.githubusercontent.com/110309314/183983401-398acd29-d9bf-468c-8e9d-2b7e4c2bee89.png)

this is what it looks like in "natural":
![Minecraft Screenshot 2022 08 10 - 20 58 59 43](https://user-images.githubusercontent.com/110309314/183983795-a514e11c-67cb-4b3b-b0de-84b1e2e58a29.png)

I certainly don't think you can backport a miniature map, but if you can I would be very grateful.

**Comment by kotmatross28729** [comment]
Or, for example, so that when you hold a map, items in your left hand are hidden

**Comment by c0508383** [comment]
> Or, for example, so that when you hold a map, items in your left hand are hidden

Going with this fix for now. Otherwise you end up growing another arm while holding a map o_O

Thank you for the report!
